# Dev 分支推送部署预览
name: Build Dev

on:
  push:
    branches:
      - dev
      - master

jobs:
  release:
    name: Build Website
    runs-on: ubuntu-latest

    steps:
      # 检出 Git 仓库
      - name: Check out git repository
        uses: actions/checkout@v4.1.1
      # 安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "18.x"
      # 复制环境变量文件
      - name: Copy .env.example
        run: |
          if [ ! -f .env ]; then
            cp .env.example .env
            echo ".env file created from .env.example."
          else
            echo ".env file already exists. Skipping the copy step."
          fi

          # 使用 sed 更新或追加 VITE_WEATHER_KEY
          if grep -q "^VITE_WEATHER_KEY=" .env; then
            sed -i'' -e "s/^VITE_WEATHER_KEY=.*/VITE_WEATHER_KEY=${{ secrets.VITE_WEATHER_KEY }}/" .env
            echo "VITE_WEATHER_KEY updated in .env."
          else
            echo "VITE_WEATHER_KEY=${{ secrets.VITE_WEATHER_KEY }}" >> .env
            echo "VITE_WEATHER_KEY added to .env."
          fi
      # 安装项目依赖
      - name: Install Dependencies
        run: npm install
      # 构建程序
      - name: Build Website
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-avz -i --delete"
            SOURCE: "dist/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: ${{ secrets.REMOTE_TARGET }}
